import type { Metadata } from "next";

import dayjs from "dayjs";
import { cn } from "@/lib/utils";
import { Roboto } from "next/font/google";
import LocalizedFormat from "dayjs/plugin/localizedFormat";

import "./globals.css";

const roboto = Roboto({
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

dayjs.extend(LocalizedFormat);

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn(roboto.className, "bg-gradient-to-r from-cyan-100 to-blue-300")}>
        <main className="min-h-screen max-w-[1920px] mx-auto">{children}</main>
      </body>
    </html>
  );
}
