import type { Metadata } from "next";

import type { FC } from "react";

import { Roboto } from "next/font/google";

import { Providers } from "./providers";

import "./globals.css";

const roboto = Roboto({
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <main className="min-h-screen grid max-w-[1920px] mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
